### ISSUE TITLE
Error response from daemon: network with name r-db already exists

### ISSUE THREAD

**Issue by leeroyaus** [ThinkR-open/devindocker#10]
I'm trying to run a docker image with a local R project using the `devindocker::launch_proj_docker` command and I receive the following error message:

`Error response from daemon: network with name r-db already exists`
 
The docker image is successfully pulled from a private repository on Docker Hub. No other containers are running in Docker.

**Comment by leeroyaus** [comment]
Sorry, I didn't realise `r-db` is the default network name

**Comment by statnmap** [comment]
Thank you.  
I like when issues are solved by themselves :smiley:
