### ISSUE TITLE
Mount additional volumes

### ISSUE THREAD

**Issue by martindut** [ThinkR-open/devindocker#3]
Hi. Very nice package that will make our lives a lot easier, thanks.
Is it possible to mount additional volumes to the container, when running devindocker::launch_proj_docker?

**Comment by statnmap** [comment]
I just added parameter `network_name` so that you can link the Docker with another Container.  
I wrote an example in this vignette : https://thinkr-open.github.io/devindocker/articles/ac-docker-network.html  
Tell me if this answers your need.

**Comment by martindut** [comment]
> I just added parameter `network_name` so that you can link the Docker with another Container.
> I wrote an example in this vignette : https://thinkr-open.github.io/devindocker/articles/ac-docker-network.html
> Tell me if this answers your need.

Fantastic, will test it out and let you know. Thanks

**Comment by martindut** [comment]
> I just added parameter `network_name` so that you can link the Docker with another Container.
> I wrote an example in this vignette : https://thinkr-open.github.io/devindocker/articles/ac-docker-network.html
> Tell me if this answers your need.

Hi, this is not 100% what I had in mind, but I can still use this.
I want to be able to pass additional volume mount parameters (-v C:/projects:/home/rstudio/projects) when launching the project in docker. I have a workaround that works, but it will be nice if I can pass this to the launch_proj_docker function.

**Comment by statnmap** [comment]
You can directly use `C:/projects` as the `project_path`. Indeed, contrary to what its name indicates, you can specify any directory for this parameter, project or not.  
This can be your complete computer path if needed...

**Comment by statnmap** [comment]
I get it. This new feature is for you then: https://thinkr-open.github.io/devindocker/articles/ac-docker-volumes.html

**Comment by martindut** [comment]
> I get it. This new feature is for you then: https://thinkr-open.github.io/devindocker/articles/ac-docker-volumes.html

Thanks so much!
